### ISSUE TITLE
backend architecture

### ISSUE THREAD

**Issue by carocad** [hiposfer/README#4]
Hey @mehdisadeghi 

Sadly you can not read my mind ( :P ) so I would like us to discuss how can we design the backend of the app.

So far my idea is to use `firebase` #1 both as a database and as a backend. I dont know how familiar you are with the concept, but recently they introduced something called Firebase functions which lets you execute small pieces of code whenever an events happens. I presume that these functions are executed in a docker container (or similar) and automatically orchestrated to scale whenever needed.

I find that really useful since it would allow us to focus mainly on coding the solutions and not on maintaining servers. Nevertheless not everything can be put there. For example the route planning algorithms need to load the complete graph-representation before doing anything and (ideally in the future) they should also update their graphs in real-time to provide better routing.

That is where `graphql` #2 comes into play. I have worked with Firebase quite some time now and the flexibility and capabilities that it provides are great but (just as in javascript) that flexibility ends up hurting on the long run without a real schema to back it up. That is where `graphql` comes into the game. We could encapsulate the `firebase` database operations through a `graphql` mechanism to provide and schema and modify it as we see fit.

Given that, we would need:
- a `/graphql` endpoint in our database to listen to and respond to app queries (clojurescript)
- a `firebase function` to respond to `/graphql` events and send information back to the app (clojurescript)
- a cluster of machines for doing routing which should ideally also scale automatically (thinking Google cloud kubernetes) (clojure)

I am looking forward to your feedback about these ideas.

PS: please send me a gmail-related account so that I can invite you to the `Firebase` project that I am currently using for testing

**Comment by mehdisadeghi** [comment]
Thanks for the info @carocad! Somehow this issue was burried amoung other GH alerts and I just see it. I'm new to firebase and on getting your invitation I looked at their introduction that how one can delegate some app logic to them. Looks very promising. I'll read about graphql and update accordingly.

**Comment by carocad** [comment]
Copy from our email conversation @mehdisadeghi:

> I would say somewhere in June to be realistic, since I don't know the
scope of the job needs to be done yet. I am still learning the whole
new toolchain. 

yeah I understand that it can be very overwhelming to get all that in such a short time. Let me knowif there is anything that I can help you with ;)

> And to make sure that we are talking about the same
thing lets define 'the routing'. For that matter I guess the app needs
a RESTful API to consume.

In theory, yes we need something like that. But actually I would prefer not to expose a RESTful API. The point of having graphql is precisely that you only need to expose one endpoint (`/graphql` for example). The clients submit queries to this endpoint and get only the information that they ask for. It is very useful once you start scaling. For the first step we dont need graphql since it would make things difficult and increase the learning curve even more. So I leave the decision to you whether or not you want to put a graphql service or a restful one to begin with. ([post from walmart on their migration to graphql](https://medium.com/walmartlabs/open-sourcing-lacinia-our-graphql-library-for-clojure-96a4ce5fc7b8))

> From your intro to Firebase I would say the
app can directly talk to the Firebase, however I don't know whether we
are aiming at a first release that only talks to the Firebase

My idea was to initially use firebase only because it is extremely flexible specially for prototyping purposes. With Firebase you can configure a server that only talks to firebase and an app that does that as well. With that configuration you can have an encrypted (async) connection between both client and server without them ever knowing about each other since firebase manages the complete communication.

> or we are going to upload (?) pieces of the backend to Firebase and run an API on
some PaaS (DigitalOcean, Heroku, AWS or alike) that the app will simultaneously use (for routing only). 

Yes, the plan on the long term is to have pieces of the backend running only in firebase (fire and forget functions for example). There are of course pieces that cannot be run there which is why we would still need a server to talk to. Routing is one of those examples.

To be honest the backend architecture is still a work in progress, and that is precisely the reason why I openned this issue, so that we can talk about it. Here is a description of possible [backend architectures](https://cloud.google.com/solutions/mobile/mobile-app-backend-services) using firebase/google cloud.

> Moreover the GraphQL specific API needs to run on the same server probably. The backend will consume Firebase API too. 

correct

> The routing itself will happen inside the frechet-dist library that you
have already implemented. So we need a backend that exposes routing
API, handles routing requests using frechet-dist library. Query/update
Firebase if necessary and returns the result back to the client (sync
or async, don't know yet). Please correct me if I'm missing anything.

not correct. The frechet-dist is only a library for computing curve similarity according to the Frechet distance (mathematical theory). The routing is part of the hypobus repo. In there you can find a `routing` namespace which contains functions for computing the shortest path between two nodes in a graph.

> In case we are moving for a RESTful API I would like to define the intended API using OpenAPI (see the initiative here: https://www.openapis.org/ and the API editor here: http://editor.swagger.io/). Of course if it is a good fit.

I am all for open standards :) but as I mentioned above I would try not to invest too much time in this since the idea is to use a graphql endpoint to handle all communication.

> Moreover, it would be great if we can talk online and accelerate things. Google hangout is a good option.

Yes, definitely ! Unfortunately it seems that my slack messages didnt reach you :( I thought we could meet today (05.05.2017)

**Comment by carocad** [comment]
@mehdisadeghi coming back to this topic after our discussion on how things are working.

Currently we have a great focus on Firebase and although it is a great platform, it also has its restrictions. One of them being that scripts must be in Javascript. Although this is doable in Clojurescript, it posses a tremendous entry barrier for someone who would like to play around with it.
Firebase and by extension Google are still lacking in development regarding their Cloud as a Platform offering.

An alternative that might be good for us is AWS (Amazon). Amazon has a single platform (not two like Firebase + Google Cloud) with support for things like containers, lambda functions in Java, Python and Javascript and a marketplace full of different tools that we could use.

I would like to re-start the discussion about the technology stack that we would use as, from what I see, our current status is not scaling :(

**Comment by carocad** [comment]
closing this as we currently are mostly experimenting and checking what works best.

I think that trying to design too much up front would be a mistake. We should still have a rough picture in our heads of where things should go but not so fixed as described in this issue.
